### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by Atinux** [jsilva-pt/nuxt-content-theme-blog#26]
First of all, nice work on this blog theme 🔥 

Some notes I suggest:
- Rename `publishedTime` to `publishedAt`
- Rename `imgUrl` to `image`
- Create another page for https://nuxtjs.blog/guide/writing#components + explaining how to overwrite all the components define by the theme + link to each component on GitHub

**Comment by jsilva-pt** [comment]
Thanks for the kind words.

I agree with the suggestions.
