### ISSUE TITLE
Tailwind is out of date 1.9.6 -> 2.0.2

### ISSUE THREAD

**Issue by SkylerStearns** [jsilva-pt/nuxt-content-theme-blog#48]
Please update this theme to include v2 of tailwind css

**Comment by jsilva-pt** [comment]
Hi @SkylerStearns,

Sorry for the delay.

Tailwindcss is provided through the [nuxt tailwindcss module](https://tailwindcss.nuxtjs.org/) which means you won't have Tailwindcss 2 until they support it.

I think it will be available soon. You can check this [issue](https://github.com/nuxt-community/tailwindcss-module/pull/203) to see its status.

**Comment by SkylerStearns** [comment]
Thanks for the update. I should have checked that myself. Thank you!
