### ISSUE TITLE
Generated URL pattern is not correct when contents on Sub Folder

### ISSUE THREAD

**Issue by shrawanx** [jsilva-pt/nuxt-content-theme-blog#73]
I do have my contents on the subfolder

```
content/
            vue/
                  first.md
                  second.md
            nuxt/
                  first.md
                  second.md
            hello.md 
```
But, when i run the project, the default homepage looks good, but the link generated for the contents in the subfolder are incorrect. i.e should generate `/vue/first` but currently is generating `/first`

The package version i am using :
```
    "@jsilva-pt/nuxt-content-theme-blog": "^0.6.0",
    "nuxt": "^2.14.12"
```

Is this anyway related to https://github.com/jsilva-pt/nuxt-content-theme-blog/issues/63 ?

**Comment by jsilva-pt** [comment]
Hi @shrawanx,

It is not related. Maybe I can improve the documentation on that part.

The subfolders inside the content folder do not dictate the generated URL. It will always be` /:slug`. You can create subfolders, but it is simply a way for you to organize your blog posts.

You can check [here](https://github.com/jsilva-pt/nuxt-content-theme-blog/tree/main/packages/nuxt-content-theme-blog/pages) the page that exists.

I also don't think it is possible to generate pages based on the content folder structure dynamically. We have to predefine the structure inside the pages folder, and I don't know what structure people will create inside the content folder.

Let me know if I was clear enough.

**Comment by shrawanx** [comment]
Hi @jsilva-pt,
I do understand now, thanks for the reply.

The list of blogs are generated on the index page which is fine, but clicking on it returns to a url which is 404.

**Comment by jsilva-pt** [comment]
@shrawanx 404 should not happen.

I will try it later today, I hope

**Comment by jsilva-pt** [comment]
Hi @shrawanx,

You can get the last patch which fixes your problem.

Thank you for reporting the issue :wink:
